//
//  PicsojagsStyleKit.swift
//  Picsojags
//
//  Created by Boy van Amstel on 20/02/2017.
//  Copyright © 2017 Danger Cove. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class PicsojagsStyleKit : NSObject {

    //// Cache

    private struct Cache {
        static let featureColor: UIColor = UIColor(red: 0.255, green: 0.843, blue: 0.000, alpha: 1.000)
    }

    //// Colors

    public dynamic class var featureColor: UIColor { return Cache.featureColor }

    //// Drawing Methods

    public dynamic class func drawPhotoPlaceholderGrid(frame: CGRect = CGRect(x: 0, y: 0, width: 120, height: 120)) {
        //// General Declarations
        // This non-generic function dramatically improves compilation times of complex expressions.
        func fastFloor(_ x: CGFloat) -> CGFloat { return floor(x) }

        //// Color Declarations
        let iconDarkColor = UIColor(red: 0.584, green: 0.584, blue: 0.584, alpha: 1.000)
        let overlayColor = UIColor(red: 0.861, green: 0.861, blue: 0.861, alpha: 0.500)


        //// Subframes
        let group: CGRect = CGRect(x: frame.minX + fastFloor((frame.width - 30) * 0.55555 + 0.5), y: frame.minY + fastFloor((frame.height - 31) * 0.49438 + 0.5), width: 30, height: 31)


        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: CGRect(x: frame.minX + 10, y: frame.minY + 10, width: frame.width - 20, height: frame.height - 20), cornerRadius: 3)
        overlayColor.setFill()
        rectanglePath.fill()


        //// Group
        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.move(to: CGPoint(x: group.minX + 29.8, y: group.minY + 26.91))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 29.2, y: group.minY + 26.23), controlPoint1: CGPoint(x: group.minX + 29.64, y: group.minY + 26.64), controlPoint2: CGPoint(x: group.minX + 29.42, y: group.minY + 26.43))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 26.61, y: group.minY + 24.65), controlPoint1: CGPoint(x: group.minX + 28.43, y: group.minY + 25.54), controlPoint2: CGPoint(x: group.minX + 27.56, y: group.minY + 25.04))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 21.66, y: group.minY + 23.68), controlPoint1: CGPoint(x: group.minX + 25.02, y: group.minY + 24.01), controlPoint2: CGPoint(x: group.minX + 23.36, y: group.minY + 23.72))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 18.92, y: group.minY + 23.87), controlPoint1: CGPoint(x: group.minX + 20.74, y: group.minY + 23.65), controlPoint2: CGPoint(x: group.minX + 19.83, y: group.minY + 23.71))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 18.38, y: group.minY + 23.96), controlPoint1: CGPoint(x: group.minX + 18.74, y: group.minY + 23.9), controlPoint2: CGPoint(x: group.minX + 18.56, y: group.minY + 23.93))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 19.1, y: group.minY + 19.89), controlPoint1: CGPoint(x: group.minX + 18.78, y: group.minY + 22.59), controlPoint2: CGPoint(x: group.minX + 19.01, y: group.minY + 21.25))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 18.98, y: group.minY + 16.59), controlPoint1: CGPoint(x: group.minX + 19.18, y: group.minY + 18.79), controlPoint2: CGPoint(x: group.minX + 19.15, y: group.minY + 17.68))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 18.28, y: group.minY + 14.14), controlPoint1: CGPoint(x: group.minX + 18.84, y: group.minY + 15.74), controlPoint2: CGPoint(x: group.minX + 18.62, y: group.minY + 14.92))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 15.17, y: group.minY + 10.56), controlPoint1: CGPoint(x: group.minX + 17.62, y: group.minY + 12.62), controlPoint2: CGPoint(x: group.minX + 16.59, y: group.minY + 11.42))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 12.57, y: group.minY + 9.48), controlPoint1: CGPoint(x: group.minX + 14.36, y: group.minY + 10.07), controlPoint2: CGPoint(x: group.minX + 13.48, y: group.minY + 9.72))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 12.44, y: group.minY + 9.42), controlPoint1: CGPoint(x: group.minX + 12.53, y: group.minY + 9.46), controlPoint2: CGPoint(x: group.minX + 12.48, y: group.minY + 9.45))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 11.54, y: group.minY + 8.77), controlPoint1: CGPoint(x: group.minX + 12.14, y: group.minY + 9.21), controlPoint2: CGPoint(x: group.minX + 11.83, y: group.minY + 9))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 10.96, y: group.minY + 8.12), controlPoint1: CGPoint(x: group.minX + 11.31, y: group.minY + 8.59), controlPoint2: CGPoint(x: group.minX + 11.06, y: group.minY + 8.42))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 10.92, y: group.minY + 8.03), controlPoint1: CGPoint(x: group.minX + 10.95, y: group.minY + 8.09), controlPoint2: CGPoint(x: group.minX + 10.93, y: group.minY + 8.06))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 10.25, y: group.minY + 7.25), controlPoint1: CGPoint(x: group.minX + 10.73, y: group.minY + 7.74), controlPoint2: CGPoint(x: group.minX + 10.5, y: group.minY + 7.49))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 9.4, y: group.minY + 6.6), controlPoint1: CGPoint(x: group.minX + 9.99, y: group.minY + 7), controlPoint2: CGPoint(x: group.minX + 9.73, y: group.minY + 6.76))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 9.3, y: group.minY + 6.48), controlPoint1: CGPoint(x: group.minX + 9.35, y: group.minY + 6.57), controlPoint2: CGPoint(x: group.minX + 9.32, y: group.minY + 6.54))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 8.72, y: group.minY + 5.06), controlPoint1: CGPoint(x: group.minX + 9.14, y: group.minY + 6), controlPoint2: CGPoint(x: group.minX + 8.96, y: group.minY + 5.51))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 8.44, y: group.minY + 4.63), controlPoint1: CGPoint(x: group.minX + 8.64, y: group.minY + 4.91), controlPoint2: CGPoint(x: group.minX + 8.53, y: group.minY + 4.77))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 8.53, y: group.minY + 3.86), controlPoint1: CGPoint(x: group.minX + 8.46, y: group.minY + 4.33), controlPoint2: CGPoint(x: group.minX + 8.5, y: group.minY + 4.09))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 8.71, y: group.minY + 1.7), controlPoint1: CGPoint(x: group.minX + 8.63, y: group.minY + 3.14), controlPoint2: CGPoint(x: group.minX + 8.7, y: group.minY + 2.43))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 8.57, y: group.minY + 0.52), controlPoint1: CGPoint(x: group.minX + 8.71, y: group.minY + 1.31), controlPoint2: CGPoint(x: group.minX + 8.69, y: group.minY + 0.91))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 8.09, y: group.minY), controlPoint1: CGPoint(x: group.minX + 8.5, y: group.minY + 0.27), controlPoint2: CGPoint(x: group.minX + 8.38, y: group.minY + 0.05))
        bezier2Path.addLine(to: CGPoint(x: group.minX + 7.97, y: group.minY))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 7.42, y: group.minY + 0.27), controlPoint1: CGPoint(x: group.minX + 7.77, y: group.minY + 0.04), controlPoint2: CGPoint(x: group.minX + 7.58, y: group.minY + 0.14))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 7.1, y: group.minY + 0.58), controlPoint1: CGPoint(x: group.minX + 7.31, y: group.minY + 0.37), controlPoint2: CGPoint(x: group.minX + 7.2, y: group.minY + 0.47))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 6.05, y: group.minY + 2.09), controlPoint1: CGPoint(x: group.minX + 6.68, y: group.minY + 1.03), controlPoint2: CGPoint(x: group.minX + 6.35, y: group.minY + 1.55))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 5.93, y: group.minY + 2.17), controlPoint1: CGPoint(x: group.minX + 6.02, y: group.minY + 2.14), controlPoint2: CGPoint(x: group.minX + 5.99, y: group.minY + 2.16))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 4.68, y: group.minY + 2.27), controlPoint1: CGPoint(x: group.minX + 5.51, y: group.minY + 2.2), controlPoint2: CGPoint(x: group.minX + 5.1, y: group.minY + 2.24))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 3.73, y: group.minY + 2.31), controlPoint1: CGPoint(x: group.minX + 4.36, y: group.minY + 2.29), controlPoint2: CGPoint(x: group.minX + 4.05, y: group.minY + 2.3))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 3.23, y: group.minY + 2.13), controlPoint1: CGPoint(x: group.minX + 3.54, y: group.minY + 2.32), controlPoint2: CGPoint(x: group.minX + 3.38, y: group.minY + 2.25))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 2.35, y: group.minY + 1.37), controlPoint1: CGPoint(x: group.minX + 2.94, y: group.minY + 1.87), controlPoint2: CGPoint(x: group.minX + 2.65, y: group.minY + 1.62))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 1.1, y: group.minY + 0.43), controlPoint1: CGPoint(x: group.minX + 1.95, y: group.minY + 1.04), controlPoint2: CGPoint(x: group.minX + 1.55, y: group.minY + 0.7))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 0.69, y: group.minY + 0.24), controlPoint1: CGPoint(x: group.minX + 0.97, y: group.minY + 0.35), controlPoint2: CGPoint(x: group.minX + 0.83, y: group.minY + 0.29))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 0.39, y: group.minY + 0.31), controlPoint1: CGPoint(x: group.minX + 0.57, y: group.minY + 0.19), controlPoint2: CGPoint(x: group.minX + 0.47, y: group.minY + 0.22))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 0.16, y: group.minY + 0.92), controlPoint1: CGPoint(x: group.minX + 0.23, y: group.minY + 0.49), controlPoint2: CGPoint(x: group.minX + 0.18, y: group.minY + 0.7))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 0.3, y: group.minY + 2.57), controlPoint1: CGPoint(x: group.minX + 0.13, y: group.minY + 1.48), controlPoint2: CGPoint(x: group.minX + 0.21, y: group.minY + 2.03))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 0.64, y: group.minY + 4.49), controlPoint1: CGPoint(x: group.minX + 0.41, y: group.minY + 3.21), controlPoint2: CGPoint(x: group.minX + 0.53, y: group.minY + 3.85))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 0.61, y: group.minY + 4.58), controlPoint1: CGPoint(x: group.minX + 0.64, y: group.minY + 4.51), controlPoint2: CGPoint(x: group.minX + 0.63, y: group.minY + 4.55))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 0.02, y: group.minY + 6.92), controlPoint1: CGPoint(x: group.minX + 0.1, y: group.minY + 5.28), controlPoint2: CGPoint(x: group.minX - 0.07, y: group.minY + 6.07))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 0.62, y: group.minY + 8.64), controlPoint1: CGPoint(x: group.minX + 0.09, y: group.minY + 7.53), controlPoint2: CGPoint(x: group.minX + 0.31, y: group.minY + 8.1))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 1.98, y: group.minY + 10.38), controlPoint1: CGPoint(x: group.minX + 0.98, y: group.minY + 9.29), controlPoint2: CGPoint(x: group.minX + 1.45, y: group.minY + 9.85))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 2.09, y: group.minY + 10.54), controlPoint1: CGPoint(x: group.minX + 2.02, y: group.minY + 10.42), controlPoint2: CGPoint(x: group.minX + 2.06, y: group.minY + 10.48))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 2.38, y: group.minY + 11.32), controlPoint1: CGPoint(x: group.minX + 2.19, y: group.minY + 10.8), controlPoint2: CGPoint(x: group.minX + 2.28, y: group.minY + 11.06))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 2.48, y: group.minY + 12.2), controlPoint1: CGPoint(x: group.minX + 2.48, y: group.minY + 11.6), controlPoint2: CGPoint(x: group.minX + 2.52, y: group.minY + 11.89))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 2.49, y: group.minY + 13.14), controlPoint1: CGPoint(x: group.minX + 2.45, y: group.minY + 12.51), controlPoint2: CGPoint(x: group.minX + 2.44, y: group.minY + 12.82))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 2.91, y: group.minY + 14.41), controlPoint1: CGPoint(x: group.minX + 2.56, y: group.minY + 13.58), controlPoint2: CGPoint(x: group.minX + 2.71, y: group.minY + 14.01))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 4.25, y: group.minY + 17.03), controlPoint1: CGPoint(x: group.minX + 3.35, y: group.minY + 15.29), controlPoint2: CGPoint(x: group.minX + 3.81, y: group.minY + 16.15))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 4.85, y: group.minY + 18.35), controlPoint1: CGPoint(x: group.minX + 4.47, y: group.minY + 17.46), controlPoint2: CGPoint(x: group.minX + 4.66, y: group.minY + 17.91))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 4.94, y: group.minY + 18.83), controlPoint1: CGPoint(x: group.minX + 4.91, y: group.minY + 18.5), controlPoint2: CGPoint(x: group.minX + 4.93, y: group.minY + 18.67))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 4.93, y: group.minY + 19.37), controlPoint1: CGPoint(x: group.minX + 4.96, y: group.minY + 19.01), controlPoint2: CGPoint(x: group.minX + 4.93, y: group.minY + 19.19))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 4.83, y: group.minY + 23.6), controlPoint1: CGPoint(x: group.minX + 4.95, y: group.minY + 20.78), controlPoint2: CGPoint(x: group.minX + 4.97, y: group.minY + 22.19))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 4.67, y: group.minY + 24.42), controlPoint1: CGPoint(x: group.minX + 4.8, y: group.minY + 23.88), controlPoint2: CGPoint(x: group.minX + 4.73, y: group.minY + 24.15))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 4.45, y: group.minY + 24.68), controlPoint1: CGPoint(x: group.minX + 4.64, y: group.minY + 24.54), controlPoint2: CGPoint(x: group.minX + 4.56, y: group.minY + 24.63))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 3.89, y: group.minY + 25.11), controlPoint1: CGPoint(x: group.minX + 4.23, y: group.minY + 24.78), controlPoint2: CGPoint(x: group.minX + 4.05, y: group.minY + 24.94))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 3.61, y: group.minY + 25.55), controlPoint1: CGPoint(x: group.minX + 3.77, y: group.minY + 25.24), controlPoint2: CGPoint(x: group.minX + 3.67, y: group.minY + 25.39))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 3.77, y: group.minY + 26.22), controlPoint1: CGPoint(x: group.minX + 3.53, y: group.minY + 25.81), controlPoint2: CGPoint(x: group.minX + 3.57, y: group.minY + 26.04))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 4.11, y: group.minY + 26.47), controlPoint1: CGPoint(x: group.minX + 3.87, y: group.minY + 26.32), controlPoint2: CGPoint(x: group.minX + 4, y: group.minY + 26.39))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 4.17, y: group.minY + 26.56), controlPoint1: CGPoint(x: group.minX + 4.14, y: group.minY + 26.49), controlPoint2: CGPoint(x: group.minX + 4.16, y: group.minY + 26.53))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 4.22, y: group.minY + 26.87), controlPoint1: CGPoint(x: group.minX + 4.19, y: group.minY + 26.66), controlPoint2: CGPoint(x: group.minX + 4.19, y: group.minY + 26.77))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 4.72, y: group.minY + 27.46), controlPoint1: CGPoint(x: group.minX + 4.29, y: group.minY + 27.15), controlPoint2: CGPoint(x: group.minX + 4.43, y: group.minY + 27.37))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 5.44, y: group.minY + 27.66), controlPoint1: CGPoint(x: group.minX + 4.96, y: group.minY + 27.54), controlPoint2: CGPoint(x: group.minX + 5.2, y: group.minY + 27.62))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 6.6, y: group.minY + 27.6), controlPoint1: CGPoint(x: group.minX + 5.83, y: group.minY + 27.74), controlPoint2: CGPoint(x: group.minX + 6.22, y: group.minY + 27.74))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 7.61, y: group.minY + 26.85), controlPoint1: CGPoint(x: group.minX + 7, y: group.minY + 27.45), controlPoint2: CGPoint(x: group.minX + 7.32, y: group.minY + 27.16))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 8.05, y: group.minY + 26.13), controlPoint1: CGPoint(x: group.minX + 7.81, y: group.minY + 26.65), controlPoint2: CGPoint(x: group.minX + 7.93, y: group.minY + 26.39))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 8.16, y: group.minY + 26.07), controlPoint1: CGPoint(x: group.minX + 8.07, y: group.minY + 26.07), controlPoint2: CGPoint(x: group.minX + 8.1, y: group.minY + 26.06))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 8.52, y: group.minY + 26.13), controlPoint1: CGPoint(x: group.minX + 8.28, y: group.minY + 26.1), controlPoint2: CGPoint(x: group.minX + 8.4, y: group.minY + 26.11))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 9.04, y: group.minY + 26.22), controlPoint1: CGPoint(x: group.minX + 8.69, y: group.minY + 26.16), controlPoint2: CGPoint(x: group.minX + 8.86, y: group.minY + 26.19))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 9, y: group.minY + 26.33), controlPoint1: CGPoint(x: group.minX + 9.02, y: group.minY + 26.26), controlPoint2: CGPoint(x: group.minX + 9.01, y: group.minY + 26.3))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 8.96, y: group.minY + 27.08), controlPoint1: CGPoint(x: group.minX + 8.92, y: group.minY + 26.58), controlPoint2: CGPoint(x: group.minX + 8.87, y: group.minY + 26.83))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 9.83, y: group.minY + 27.86), controlPoint1: CGPoint(x: group.minX + 9.1, y: group.minY + 27.5), controlPoint2: CGPoint(x: group.minX + 9.41, y: group.minY + 27.75))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 10.51, y: group.minY + 27.94), controlPoint1: CGPoint(x: group.minX + 10.05, y: group.minY + 27.92), controlPoint2: CGPoint(x: group.minX + 10.28, y: group.minY + 27.94))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 13.21, y: group.minY + 27.63), controlPoint1: CGPoint(x: group.minX + 11.42, y: group.minY + 27.96), controlPoint2: CGPoint(x: group.minX + 12.32, y: group.minY + 27.82))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 15.1, y: group.minY + 27.19), controlPoint1: CGPoint(x: group.minX + 13.84, y: group.minY + 27.5), controlPoint2: CGPoint(x: group.minX + 14.47, y: group.minY + 27.34))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 15.2, y: group.minY + 27.2), controlPoint1: CGPoint(x: group.minX + 15.13, y: group.minY + 27.18), controlPoint2: CGPoint(x: group.minX + 15.17, y: group.minY + 27.18))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 16.71, y: group.minY + 27.49), controlPoint1: CGPoint(x: group.minX + 15.67, y: group.minY + 27.45), controlPoint2: CGPoint(x: group.minX + 16.18, y: group.minY + 27.53))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 18.41, y: group.minY + 26.99), controlPoint1: CGPoint(x: group.minX + 17.32, y: group.minY + 27.45), controlPoint2: CGPoint(x: group.minX + 17.88, y: group.minY + 27.27))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 19.45, y: group.minY + 26.56), controlPoint1: CGPoint(x: group.minX + 18.75, y: group.minY + 26.82), controlPoint2: CGPoint(x: group.minX + 19.09, y: group.minY + 26.67))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 22.46, y: group.minY + 26.12), controlPoint1: CGPoint(x: group.minX + 20.43, y: group.minY + 26.27), controlPoint2: CGPoint(x: group.minX + 21.44, y: group.minY + 26.15))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 24.73, y: group.minY + 26.26), controlPoint1: CGPoint(x: group.minX + 23.22, y: group.minY + 26.1), controlPoint2: CGPoint(x: group.minX + 23.98, y: group.minY + 26.14))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 26.26, y: group.minY + 26.7), controlPoint1: CGPoint(x: group.minX + 25.26, y: group.minY + 26.35), controlPoint2: CGPoint(x: group.minX + 25.78, y: group.minY + 26.47))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 27.01, y: group.minY + 27.23), controlPoint1: CGPoint(x: group.minX + 26.54, y: group.minY + 26.83), controlPoint2: CGPoint(x: group.minX + 26.81, y: group.minY + 26.99))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 27, y: group.minY + 28.01), controlPoint1: CGPoint(x: group.minX + 27.24, y: group.minY + 27.49), controlPoint2: CGPoint(x: group.minX + 27.23, y: group.minY + 27.75))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 26.88, y: group.minY + 28.12), controlPoint1: CGPoint(x: group.minX + 26.97, y: group.minY + 28.05), controlPoint2: CGPoint(x: group.minX + 26.93, y: group.minY + 28.09))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 25.88, y: group.minY + 28.65), controlPoint1: CGPoint(x: group.minX + 26.59, y: group.minY + 28.37), controlPoint2: CGPoint(x: group.minX + 26.24, y: group.minY + 28.52))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 23.42, y: group.minY + 29.3), controlPoint1: CGPoint(x: group.minX + 25.08, y: group.minY + 28.95), controlPoint2: CGPoint(x: group.minX + 24.26, y: group.minY + 29.14))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 22.72, y: group.minY + 29.68), controlPoint1: CGPoint(x: group.minX + 23, y: group.minY + 29.37), controlPoint2: CGPoint(x: group.minX + 23, y: group.minY + 29.37))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 22.42, y: group.minY + 30.16), controlPoint1: CGPoint(x: group.minX + 22.59, y: group.minY + 29.82), controlPoint2: CGPoint(x: group.minX + 22.48, y: group.minY + 29.97))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 22.58, y: group.minY + 30.67), controlPoint1: CGPoint(x: group.minX + 22.36, y: group.minY + 30.36), controlPoint2: CGPoint(x: group.minX + 22.41, y: group.minY + 30.54))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 22.73, y: group.minY + 30.77), controlPoint1: CGPoint(x: group.minX + 22.62, y: group.minY + 30.71), controlPoint2: CGPoint(x: group.minX + 22.67, y: group.minY + 30.74))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 23.85, y: group.minY + 31), controlPoint1: CGPoint(x: group.minX + 23.08, y: group.minY + 30.94), controlPoint2: CGPoint(x: group.minX + 23.46, y: group.minY + 30.99))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 25.92, y: group.minY + 30.69), controlPoint1: CGPoint(x: group.minX + 24.56, y: group.minY + 31.02), controlPoint2: CGPoint(x: group.minX + 25.24, y: group.minY + 30.88))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 28.78, y: group.minY + 29.39), controlPoint1: CGPoint(x: group.minX + 26.94, y: group.minY + 30.41), controlPoint2: CGPoint(x: group.minX + 27.91, y: group.minY + 30.01))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 29.74, y: group.minY + 28.43), controlPoint1: CGPoint(x: group.minX + 29.16, y: group.minY + 29.13), controlPoint2: CGPoint(x: group.minX + 29.5, y: group.minY + 28.83))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 29.8, y: group.minY + 26.91), controlPoint1: CGPoint(x: group.minX + 30.05, y: group.minY + 27.94), controlPoint2: CGPoint(x: group.minX + 30.1, y: group.minY + 27.43))
        bezier2Path.close()
        iconDarkColor.setFill()
        bezier2Path.fill()
    }

    public dynamic class func drawPhotoPlaceholderFull(frame: CGRect = CGRect(x: 0, y: 0, width: 120, height: 120)) {
        //// General Declarations
        // This non-generic function dramatically improves compilation times of complex expressions.
        func fastFloor(_ x: CGFloat) -> CGFloat { return floor(x) }

        //// Color Declarations
        let iconLightColor = UIColor(red: 0.218, green: 0.218, blue: 0.218, alpha: 1.000)


        //// Subframes
        let group: CGRect = CGRect(x: frame.minX + fastFloor((frame.width - 115) * 0.59988 + 0.5), y: frame.minY + fastFloor((frame.height - 120) / 2 + 0.5), width: 115, height: 120)


        //// Group
        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.move(to: CGPoint(x: group.minX + 114.23, y: group.minY + 104.18))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 111.91, y: group.minY + 101.52), controlPoint1: CGPoint(x: group.minX + 113.64, y: group.minY + 103.14), controlPoint2: CGPoint(x: group.minX + 112.79, y: group.minY + 102.32))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 101.99, y: group.minY + 95.44), controlPoint1: CGPoint(x: group.minX + 108.99, y: group.minY + 98.87), controlPoint2: CGPoint(x: group.minX + 105.63, y: group.minY + 96.92))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 83.02, y: group.minY + 91.65), controlPoint1: CGPoint(x: group.minX + 95.91, y: group.minY + 92.95), controlPoint2: CGPoint(x: group.minX + 89.56, y: group.minY + 91.81))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 72.54, y: group.minY + 92.39), controlPoint1: CGPoint(x: group.minX + 79.51, y: group.minY + 91.57), controlPoint2: CGPoint(x: group.minX + 76.01, y: group.minY + 91.8))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 70.44, y: group.minY + 92.76), controlPoint1: CGPoint(x: group.minX + 71.85, y: group.minY + 92.51), controlPoint2: CGPoint(x: group.minX + 71.16, y: group.minY + 92.63))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 73.22, y: group.minY + 77), controlPoint1: CGPoint(x: group.minX + 71.98, y: group.minY + 87.44), controlPoint2: CGPoint(x: group.minX + 72.86, y: group.minY + 82.26))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 72.74, y: group.minY + 64.2), controlPoint1: CGPoint(x: group.minX + 73.52, y: group.minY + 72.72), controlPoint2: CGPoint(x: group.minX + 73.41, y: group.minY + 68.45))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 70.06, y: group.minY + 54.73), controlPoint1: CGPoint(x: group.minX + 72.22, y: group.minY + 60.94), controlPoint2: CGPoint(x: group.minX + 71.37, y: group.minY + 57.77))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 58.15, y: group.minY + 40.88), controlPoint1: CGPoint(x: group.minX + 67.54, y: group.minY + 48.87), controlPoint2: CGPoint(x: group.minX + 63.6, y: group.minY + 44.22))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 48.18, y: group.minY + 36.68), controlPoint1: CGPoint(x: group.minX + 55.04, y: group.minY + 38.97), controlPoint2: CGPoint(x: group.minX + 51.69, y: group.minY + 37.63))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 47.7, y: group.minY + 36.48), controlPoint1: CGPoint(x: group.minX + 48.01, y: group.minY + 36.64), controlPoint2: CGPoint(x: group.minX + 47.84, y: group.minY + 36.58))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 44.24, y: group.minY + 33.95), controlPoint1: CGPoint(x: group.minX + 46.54, y: group.minY + 35.64), controlPoint2: CGPoint(x: group.minX + 45.37, y: group.minY + 34.83))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 42.02, y: group.minY + 31.42), controlPoint1: CGPoint(x: group.minX + 43.35, y: group.minY + 33.26), controlPoint2: CGPoint(x: group.minX + 42.41, y: group.minY + 32.58))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 41.84, y: group.minY + 31.1), controlPoint1: CGPoint(x: group.minX + 41.98, y: group.minY + 31.31), controlPoint2: CGPoint(x: group.minX + 41.91, y: group.minY + 31.21))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 39.29, y: group.minY + 28.06), controlPoint1: CGPoint(x: group.minX + 41.12, y: group.minY + 29.98), controlPoint2: CGPoint(x: group.minX + 40.24, y: group.minY + 28.99))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 36.04, y: group.minY + 25.54), controlPoint1: CGPoint(x: group.minX + 38.31, y: group.minY + 27.09), controlPoint2: CGPoint(x: group.minX + 37.28, y: group.minY + 26.18))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 35.66, y: group.minY + 25.09), controlPoint1: CGPoint(x: group.minX + 35.84, y: group.minY + 25.44), controlPoint2: CGPoint(x: group.minX + 35.73, y: group.minY + 25.31))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 33.43, y: group.minY + 19.57), controlPoint1: CGPoint(x: group.minX + 35.02, y: group.minY + 23.21), controlPoint2: CGPoint(x: group.minX + 34.35, y: group.minY + 21.34))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 32.34, y: group.minY + 17.93), controlPoint1: CGPoint(x: group.minX + 33.13, y: group.minY + 18.99), controlPoint2: CGPoint(x: group.minX + 32.7, y: group.minY + 18.48))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 32.7, y: group.minY + 14.92), controlPoint1: CGPoint(x: group.minX + 32.42, y: group.minY + 16.77), controlPoint2: CGPoint(x: group.minX + 32.57, y: group.minY + 15.85))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 33.37, y: group.minY + 6.6), controlPoint1: CGPoint(x: group.minX + 33.08, y: group.minY + 12.16), controlPoint2: CGPoint(x: group.minX + 33.37, y: group.minY + 9.39))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 32.87, y: group.minY + 2.02), controlPoint1: CGPoint(x: group.minX + 33.37, y: group.minY + 5.05), controlPoint2: CGPoint(x: group.minX + 33.31, y: group.minY + 3.51))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 31, y: group.minY), controlPoint1: CGPoint(x: group.minX + 32.57, y: group.minY + 1.04), controlPoint2: CGPoint(x: group.minX + 32.12, y: group.minY + 0.21))
        bezier2Path.addLine(to: CGPoint(x: group.minX + 30.57, y: group.minY))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 28.46, y: group.minY + 1.05), controlPoint1: CGPoint(x: group.minX + 29.77, y: group.minY + 0.16), controlPoint2: CGPoint(x: group.minX + 29.07, y: group.minY + 0.52))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 27.22, y: group.minY + 2.23), controlPoint1: CGPoint(x: group.minX + 28.02, y: group.minY + 1.42), controlPoint2: CGPoint(x: group.minX + 27.6, y: group.minY + 1.81))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 23.19, y: group.minY + 8.1), controlPoint1: CGPoint(x: group.minX + 25.6, y: group.minY + 3.99), controlPoint2: CGPoint(x: group.minX + 24.34, y: group.minY + 6.01))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 22.73, y: group.minY + 8.4), controlPoint1: CGPoint(x: group.minX + 23.08, y: group.minY + 8.3), controlPoint2: CGPoint(x: group.minX + 22.95, y: group.minY + 8.38))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 17.94, y: group.minY + 8.79), controlPoint1: CGPoint(x: group.minX + 21.14, y: group.minY + 8.52), controlPoint2: CGPoint(x: group.minX + 19.54, y: group.minY + 8.69))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 14.31, y: group.minY + 8.95), controlPoint1: CGPoint(x: group.minX + 16.73, y: group.minY + 8.88), controlPoint2: CGPoint(x: group.minX + 15.52, y: group.minY + 8.89))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 12.4, y: group.minY + 8.23), controlPoint1: CGPoint(x: group.minX + 13.56, y: group.minY + 8.98), controlPoint2: CGPoint(x: group.minX + 12.96, y: group.minY + 8.73))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 9, y: group.minY + 5.31), controlPoint1: CGPoint(x: group.minX + 11.29, y: group.minY + 7.24), controlPoint2: CGPoint(x: group.minX + 10.14, y: group.minY + 6.28))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 4.22, y: group.minY + 1.67), controlPoint1: CGPoint(x: group.minX + 7.47, y: group.minY + 4.02), controlPoint2: CGPoint(x: group.minX + 5.94, y: group.minY + 2.71))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 2.63, y: group.minY + 0.92), controlPoint1: CGPoint(x: group.minX + 3.72, y: group.minY + 1.37), controlPoint2: CGPoint(x: group.minX + 3.17, y: group.minY + 1.13))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 1.48, y: group.minY + 1.22), controlPoint1: CGPoint(x: group.minX + 2.2, y: group.minY + 0.75), controlPoint2: CGPoint(x: group.minX + 1.81, y: group.minY + 0.85))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 0.63, y: group.minY + 3.56), controlPoint1: CGPoint(x: group.minX + 0.87, y: group.minY + 1.89), controlPoint2: CGPoint(x: group.minX + 0.68, y: group.minY + 2.7))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 1.16, y: group.minY + 9.96), controlPoint1: CGPoint(x: group.minX + 0.5, y: group.minY + 5.72), controlPoint2: CGPoint(x: group.minX + 0.82, y: group.minY + 7.84))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 2.44, y: group.minY + 17.36), controlPoint1: CGPoint(x: group.minX + 1.56, y: group.minY + 12.43), controlPoint2: CGPoint(x: group.minX + 2.01, y: group.minY + 14.89))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 2.36, y: group.minY + 17.72), controlPoint1: CGPoint(x: group.minX + 2.46, y: group.minY + 17.48), controlPoint2: CGPoint(x: group.minX + 2.42, y: group.minY + 17.63))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 0.09, y: group.minY + 26.79), controlPoint1: CGPoint(x: group.minX + 0.39, y: group.minY + 20.44), controlPoint2: CGPoint(x: group.minX - 0.26, y: group.minY + 23.49))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 2.36, y: group.minY + 33.44), controlPoint1: CGPoint(x: group.minX + 0.35, y: group.minY + 29.17), controlPoint2: CGPoint(x: group.minX + 1.19, y: group.minY + 31.36))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 7.58, y: group.minY + 40.17), controlPoint1: CGPoint(x: group.minX + 3.76, y: group.minY + 35.94), controlPoint2: CGPoint(x: group.minX + 5.57, y: group.minY + 38.13))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 8, y: group.minY + 40.8), controlPoint1: CGPoint(x: group.minX + 7.76, y: group.minY + 40.35), controlPoint2: CGPoint(x: group.minX + 7.91, y: group.minY + 40.57))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 9.11, y: group.minY + 43.8), controlPoint1: CGPoint(x: group.minX + 8.39, y: group.minY + 41.8), controlPoint2: CGPoint(x: group.minX + 8.75, y: group.minY + 42.8))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 9.53, y: group.minY + 47.22), controlPoint1: CGPoint(x: group.minX + 9.5, y: group.minY + 44.91), controlPoint2: CGPoint(x: group.minX + 9.65, y: group.minY + 46.04))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 9.55, y: group.minY + 50.85), controlPoint1: CGPoint(x: group.minX + 9.4, y: group.minY + 48.43), controlPoint2: CGPoint(x: group.minX + 9.36, y: group.minY + 49.64))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 11.16, y: group.minY + 55.79), controlPoint1: CGPoint(x: group.minX + 9.82, y: group.minY + 52.58), controlPoint2: CGPoint(x: group.minX + 10.38, y: group.minY + 54.23))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 16.29, y: group.minY + 65.92), controlPoint1: CGPoint(x: group.minX + 12.85, y: group.minY + 59.17), controlPoint2: CGPoint(x: group.minX + 14.61, y: group.minY + 62.53))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 18.58, y: group.minY + 71.04), controlPoint1: CGPoint(x: group.minX + 17.12, y: group.minY + 67.59), controlPoint2: CGPoint(x: group.minX + 17.87, y: group.minY + 69.31))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 18.95, y: group.minY + 72.88), controlPoint1: CGPoint(x: group.minX + 18.82, y: group.minY + 71.61), controlPoint2: CGPoint(x: group.minX + 18.91, y: group.minY + 72.26))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 18.92, y: group.minY + 74.99), controlPoint1: CGPoint(x: group.minX + 19, y: group.minY + 73.58), controlPoint2: CGPoint(x: group.minX + 18.91, y: group.minY + 74.28))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 18.5, y: group.minY + 91.35), controlPoint1: CGPoint(x: group.minX + 18.99, y: group.minY + 80.45), controlPoint2: CGPoint(x: group.minX + 19.06, y: group.minY + 85.91))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 17.89, y: group.minY + 94.55), controlPoint1: CGPoint(x: group.minX + 18.39, y: group.minY + 92.43), controlPoint2: CGPoint(x: group.minX + 18.12, y: group.minY + 93.49))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 17.04, y: group.minY + 95.54), controlPoint1: CGPoint(x: group.minX + 17.79, y: group.minY + 95.01), controlPoint2: CGPoint(x: group.minX + 17.5, y: group.minY + 95.32))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 14.9, y: group.minY + 97.21), controlPoint1: CGPoint(x: group.minX + 16.21, y: group.minY + 95.93), controlPoint2: CGPoint(x: group.minX + 15.51, y: group.minY + 96.52))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 13.85, y: group.minY + 98.92), controlPoint1: CGPoint(x: group.minX + 14.45, y: group.minY + 97.72), controlPoint2: CGPoint(x: group.minX + 14.07, y: group.minY + 98.26))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 14.44, y: group.minY + 101.52), controlPoint1: CGPoint(x: group.minX + 13.52, y: group.minY + 99.9), controlPoint2: CGPoint(x: group.minX + 13.69, y: group.minY + 100.8))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 15.75, y: group.minY + 102.48), controlPoint1: CGPoint(x: group.minX + 14.83, y: group.minY + 101.89), controlPoint2: CGPoint(x: group.minX + 15.32, y: group.minY + 102.15))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 15.97, y: group.minY + 102.81), controlPoint1: CGPoint(x: group.minX + 15.85, y: group.minY + 102.56), controlPoint2: CGPoint(x: group.minX + 15.94, y: group.minY + 102.69))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 16.18, y: group.minY + 104.03), controlPoint1: CGPoint(x: group.minX + 16.05, y: group.minY + 103.21), controlPoint2: CGPoint(x: group.minX + 16.08, y: group.minY + 103.63))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 18.11, y: group.minY + 106.31), controlPoint1: CGPoint(x: group.minX + 16.44, y: group.minY + 105.1), controlPoint2: CGPoint(x: group.minX + 16.99, y: group.minY + 105.96))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 20.84, y: group.minY + 107.09), controlPoint1: CGPoint(x: group.minX + 19.01, y: group.minY + 106.59), controlPoint2: CGPoint(x: group.minX + 19.92, y: group.minY + 106.91))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 25.28, y: group.minY + 106.84), controlPoint1: CGPoint(x: group.minX + 22.33, y: group.minY + 107.38), controlPoint2: CGPoint(x: group.minX + 23.84, y: group.minY + 107.38))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 29.19, y: group.minY + 103.95), controlPoint1: CGPoint(x: group.minX + 26.85, y: group.minY + 106.25), controlPoint2: CGPoint(x: group.minX + 28.06, y: group.minY + 105.13))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 30.85, y: group.minY + 101.16), controlPoint1: CGPoint(x: group.minX + 29.95, y: group.minY + 103.15), controlPoint2: CGPoint(x: group.minX + 30.41, y: group.minY + 102.15))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 31.3, y: group.minY + 100.93), controlPoint1: CGPoint(x: group.minX + 30.95, y: group.minY + 100.93), controlPoint2: CGPoint(x: group.minX + 31.07, y: group.minY + 100.88))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 32.67, y: group.minY + 101.17), controlPoint1: CGPoint(x: group.minX + 31.75, y: group.minY + 101.02), controlPoint2: CGPoint(x: group.minX + 32.21, y: group.minY + 101.09))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 34.65, y: group.minY + 101.51), controlPoint1: CGPoint(x: group.minX + 33.32, y: group.minY + 101.28), controlPoint2: CGPoint(x: group.minX + 33.97, y: group.minY + 101.39))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 34.5, y: group.minY + 101.91), controlPoint1: CGPoint(x: group.minX + 34.59, y: group.minY + 101.67), controlPoint2: CGPoint(x: group.minX + 34.54, y: group.minY + 101.79))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 34.34, y: group.minY + 104.84), controlPoint1: CGPoint(x: group.minX + 34.18, y: group.minY + 102.87), controlPoint2: CGPoint(x: group.minX + 34, y: group.minY + 103.86))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 37.67, y: group.minY + 107.85), controlPoint1: CGPoint(x: group.minX + 34.89, y: group.minY + 106.44), controlPoint2: CGPoint(x: group.minX + 36.07, y: group.minY + 107.43))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 40.28, y: group.minY + 108.17), controlPoint1: CGPoint(x: group.minX + 38.51, y: group.minY + 108.07), controlPoint2: CGPoint(x: group.minX + 39.4, y: group.minY + 108.15))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 50.64, y: group.minY + 106.96), controlPoint1: CGPoint(x: group.minX + 43.78, y: group.minY + 108.24), controlPoint2: CGPoint(x: group.minX + 47.23, y: group.minY + 107.68))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 57.89, y: group.minY + 105.26), controlPoint1: CGPoint(x: group.minX + 53.07, y: group.minY + 106.45), controlPoint2: CGPoint(x: group.minX + 55.47, y: group.minY + 105.83))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 58.26, y: group.minY + 105.28), controlPoint1: CGPoint(x: group.minX + 58, y: group.minY + 105.23), controlPoint2: CGPoint(x: group.minX + 58.16, y: group.minY + 105.23))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 64.06, y: group.minY + 106.42), controlPoint1: CGPoint(x: group.minX + 60.08, y: group.minY + 106.26), controlPoint2: CGPoint(x: group.minX + 62.03, y: group.minY + 106.55))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 70.58, y: group.minY + 104.48), controlPoint1: CGPoint(x: group.minX + 66.38, y: group.minY + 106.27), controlPoint2: CGPoint(x: group.minX + 68.53, y: group.minY + 105.55))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 74.56, y: group.minY + 102.83), controlPoint1: CGPoint(x: group.minX + 71.86, y: group.minY + 103.81), controlPoint2: CGPoint(x: group.minX + 73.18, y: group.minY + 103.25))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 86.09, y: group.minY + 101.11), controlPoint1: CGPoint(x: group.minX + 78.32, y: group.minY + 101.69), controlPoint2: CGPoint(x: group.minX + 82.18, y: group.minY + 101.23))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 94.82, y: group.minY + 101.66), controlPoint1: CGPoint(x: group.minX + 89.02, y: group.minY + 101.03), controlPoint2: CGPoint(x: group.minX + 91.93, y: group.minY + 101.18))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 100.67, y: group.minY + 103.35), controlPoint1: CGPoint(x: group.minX + 96.83, y: group.minY + 102), controlPoint2: CGPoint(x: group.minX + 98.81, y: group.minY + 102.48))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 103.55, y: group.minY + 105.41), controlPoint1: CGPoint(x: group.minX + 101.75, y: group.minY + 103.86), controlPoint2: CGPoint(x: group.minX + 102.77, y: group.minY + 104.48))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 103.5, y: group.minY + 108.42), controlPoint1: CGPoint(x: group.minX + 104.4, y: group.minY + 106.42), controlPoint2: CGPoint(x: group.minX + 104.39, y: group.minY + 107.43))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 103.06, y: group.minY + 108.85), controlPoint1: CGPoint(x: group.minX + 103.37, y: group.minY + 108.57), controlPoint2: CGPoint(x: group.minX + 103.21, y: group.minY + 108.72))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 99.19, y: group.minY + 110.92), controlPoint1: CGPoint(x: group.minX + 101.91, y: group.minY + 109.8), controlPoint2: CGPoint(x: group.minX + 100.57, y: group.minY + 110.4))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 89.79, y: group.minY + 113.4), controlPoint1: CGPoint(x: group.minX + 96.15, y: group.minY + 112.08), controlPoint2: CGPoint(x: group.minX + 92.99, y: group.minY + 112.81))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 87.1, y: group.minY + 114.87), controlPoint1: CGPoint(x: group.minX + 88.18, y: group.minY + 113.71), controlPoint2: CGPoint(x: group.minX + 88.17, y: group.minY + 113.68))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 85.95, y: group.minY + 116.73), controlPoint1: CGPoint(x: group.minX + 86.61, y: group.minY + 115.42), controlPoint2: CGPoint(x: group.minX + 86.17, y: group.minY + 116.01))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 86.55, y: group.minY + 118.73), controlPoint1: CGPoint(x: group.minX + 85.71, y: group.minY + 117.53), controlPoint2: CGPoint(x: group.minX + 85.9, y: group.minY + 118.21))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 87.12, y: group.minY + 119.1), controlPoint1: CGPoint(x: group.minX + 86.72, y: group.minY + 118.88), controlPoint2: CGPoint(x: group.minX + 86.92, y: group.minY + 119.01))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 91.43, y: group.minY + 119.99), controlPoint1: CGPoint(x: group.minX + 88.48, y: group.minY + 119.76), controlPoint2: CGPoint(x: group.minX + 89.95, y: group.minY + 119.96))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 99.35, y: group.minY + 118.81), controlPoint1: CGPoint(x: group.minX + 94.14, y: group.minY + 120.06), controlPoint2: CGPoint(x: group.minX + 96.76, y: group.minY + 119.54))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 110.32, y: group.minY + 113.78), controlPoint1: CGPoint(x: group.minX + 103.27, y: group.minY + 117.71), controlPoint2: CGPoint(x: group.minX + 106.98, y: group.minY + 116.16))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 114.01, y: group.minY + 110.06), controlPoint1: CGPoint(x: group.minX + 111.76, y: group.minY + 112.76), controlPoint2: CGPoint(x: group.minX + 113.07, y: group.minY + 111.58))
        bezier2Path.addCurve(to: CGPoint(x: group.minX + 114.23, y: group.minY + 104.18), controlPoint1: CGPoint(x: group.minX + 115.2, y: group.minY + 108.14), controlPoint2: CGPoint(x: group.minX + 115.37, y: group.minY + 106.18))
        bezier2Path.close()
        iconLightColor.setFill()
        bezier2Path.fill()
    }

    public dynamic class func drawCanvas1(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 360, height: 375), resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 360, height: 375), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 360, y: resizedFrame.height / 375)
        
        context.restoreGState()

    }

    //// Generated Images

    public dynamic class func imageOfPhotoPlaceholderGrid(imageSize: CGSize = CGSize(width: 120, height: 120)) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(imageSize, false, 0)
            PicsojagsStyleKit.drawPhotoPlaceholderGrid(frame: CGRect(x: 0, y: 0, width: imageSize.width, height: imageSize.height))

        let imageOfPhotoPlaceholderGrid = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return imageOfPhotoPlaceholderGrid
    }

    public dynamic class func imageOfPhotoPlaceholderFull(imageSize: CGSize = CGSize(width: 120, height: 120)) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(imageSize, false, 0)
            PicsojagsStyleKit.drawPhotoPlaceholderFull(frame: CGRect(x: 0, y: 0, width: imageSize.width, height: imageSize.height))

        let imageOfPhotoPlaceholderFull = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return imageOfPhotoPlaceholderFull
    }




    @objc public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
